backend:
  name: git-gateway
  branch: main

locale: pt
publish_mode: editorial_workflow
media_folder: "/assets/imagens/uploads"
logo_url: "/assets/imagens/cmsimage.png"
site_url: https://amazing-joliot-be8aab.netlify.app
local_backend: true
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "/_posts"
    create: true
    preview_path_date_field: "date"
    preview_path: "{{year}}/{{month}}/{{day}}/{{title}}.html"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Título da postagem", name: "title", widget: "string"}
      - {label: "Data de publicação", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm"}
      - {label: "Texto", name: "body", widget: "markdown"}
  - name: "politicas"
    label: "Políticas"
    folder: "/"
    filter: {field: "layout", value: "politicas"}
    create: true
    preview_path: "/{{title}}.html"
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "politicas"}
      - {label: "Título da página", name: "title", widget: "string"}
      - {label: "Texto", name: "body", widget: "markdown"}
  - name: "paginas"
    label: "Páginas"
    folder: "/"
    filter: {field: "layout", value: "default"}
    create: true
    preview_path: "/{{title}}.html"
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Título da página", name: "title", widget: "string"}
      - {label: "Título no banner", name: "bannertitle", widget: "string"}
      - {label: "Subtítulo", name: "bannersubtitle", widget: "string"}
      - {label: "Botão", name: "buttontext", widget: "string", required: false}
      - {label: "Link do botão", name: "buttonlink", widget: "string", required: false}
      - {label: "Imagem de fundo", name: "bannerimage", widget: "image"}
      - {label: "Texto", name: "body", widget: "markdown"}
  - label: "Configurações"
    name: "configuracoes"
    files:
      - label: "Página Inicial"
        name: "paginainicial"
        file: "/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
          - {label: "Título da página", name: "title", widget: "string"}
          - {label: "Título no banner", name: "bannertitle", widget: "string"}
          - {label: "Subtítulo", name: "bannersubtitle", widget: "string"}
          - {label: "Botão", name: "buttontext", widget: "string", required: false}
          - {label: "Link do botão", name: "buttonlink", widget: "string", required: false}
          - {label: "Imagem de fundo", name: "bannerimage", widget: "image"}
          - {label: "Texto", name: "body", widget: "markdown"}  
      - label: "Menu lateral"
        name: "menulateral"
        file: "/_data/menu.yml"
        fields:
          - label: "Itens do menu"
            name: "nav"
            widget: "list"
            label_singular: "item"
            allow_add: true
            collapsed: false
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
      - label: "Nome e descrição"
        name: "metaconfigs"
        file: "/_config.yml"
        fields:
          - { label: "Nome", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "string" }
editor:
  preview: false